unipaulistana.web/Controllers/SolicitacaoController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using System.IO;
    using unipaulistana.web.Helper;
    using Microsoft.AspNetCore.Hosting;
    using unipaulistana.web.extensions;

    [Authorize]
    public class SolicitacaoController : Controller
    {
        public SolicitacaoController(ISolicitacaoService solicitacaoService,
                                    IClienteService clienteService,
                                    IUsuarioService usuarioService,
                                    IDepartamentoService departamentoService,
                                    IHostingEnvironment hostingEnvironment)
        {
            this.solicitacaoService = solicitacaoService;
            this.clienteService = clienteService;
            this.usuarioService = usuarioService;
            this.hostingEnvironment = hostingEnvironment;
            this.departamentoService = departamentoService;
        }

        readonly ISolicitacaoService solicitacaoService;
        readonly IClienteService clienteService;
        readonly IUsuarioService usuarioService;
        readonly IDepartamentoService departamentoService;
        readonly IHostingEnvironment hostingEnvironment;

        [Authorize(Policy = "PermiteListarSolicitacao")]
        public IActionResult Index()
        {
            if (TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            }

            ViewBag.ListarSolicitacoes = this.solicitacaoService.ObterStatusEmAbertoPorUsuario(User.GetUserID());
            return View();
        }


        [HttpPost]
        public IActionResult Index(SolicitacaoPesquisar solicitacaoPesquisar)
        {
            ViewBag.ListarSolicitacoes = this.solicitacaoService.Filtrar(solicitacaoPesquisar);
            return View();
        }

        [Authorize(Policy = "PermiteCriarSolicitacao")]
        public IActionResult Criar()
        {
            AtualizarListas();
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Solicitacao dados)
        {
            try
            {
                this.solicitacaoService.Adicionar(dados, User.GetUserID());
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        [Authorize(Policy = "PermiteAlterarSolicitacao")]
        public IActionResult Alterar(int id)
        {
            if (TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            }

            AtualizarListas();
            return View(this.solicitacaoService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(Solicitacao dados)
        {
            try
            {
                this.solicitacaoService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Solicitação atualizada com sucesso.";
                return RedirectToAction("Alterar", dados.SolicitacaoID);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar a solicitação:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        void AtualizarListas()
        {
            ViewBag.ListarDepartamentos = this.departamentoService.ObterTodos();
            ViewBag.ListarCliente = this.clienteService.ObterTodos();
            ViewBag.ListarUsuarios = this.usuarioService.ObterTodos();
        }

        [Authorize(Policy = "PermiteConcluirSolicitacao")]
        public IActionResult ConcluirSolicitacao(int id)
        {
            return View();
        }


        [HttpPost]
        [Authorize(Policy = "PermiteAlterarSolicitacao")]
        public IActionResult AdicionarItem(SolicitacaoItem solicitacaoItem)
        {
            if (!string.IsNullOrEmpty(solicitacaoItem.Descricao))
                this.solicitacaoService.AdicionarItem(solicitacaoItem, User.GetUserID());
                
            return RedirectToAction("Alterar", new { id = solicitacaoItem.SolicitacaoID });
        }
    }
}

unipaulistana.web/ViewComponents/solicitacaoItensInserirViewComponent.cs
namespace LoginViewComponent
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using System.Linq;

    public class SolicitacaoItensInserirViewComponent : ViewComponent
    {
        public SolicitacaoItensInserirViewComponent(ISolicitacaoService solicitacaoService)
        {
            this.solicitacaoService = solicitacaoService;
        }

        readonly ISolicitacaoService solicitacaoService;

        public async Task<IViewComponentResult> InvokeAsync(int solicitacaoID)
        {
           return View("_solicitacaoItensInserir", new SolicitacaoItem(solicitacaoID));
        }
    }
}

unipaulistana.web/ViewComponents/solicitacaoItensViewComponent.cs
namespace LoginViewComponent
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using System.Linq;

    public class SolicitacaoItensViewComponent : ViewComponent
    {
        public SolicitacaoItensViewComponent(ISolicitacaoService solicitacaoService)
        {
            this.solicitacaoService = solicitacaoService;
        }

        readonly ISolicitacaoService solicitacaoService;

        public async Task<IViewComponentResult> InvokeAsync(int solicitacaoID)
        {
           return View("_solicitacaoItens", this.solicitacaoService.ObterPorSolicitacaoItens(solicitacaoID).OrderByDescending(x=> x.Data));
        }
    }
}

unipaulistana.web/Views/Solicitacao/Alterar.cshtml
@model unipaulistana.model.Solicitacao

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Alterar solicitação</h3>
		</div>
		<div class="module-body">
			<form asp-action="Alterar" class="form-horizontal row-fluid">
				
                <input type="hidden" asp-for="SolicitacaoID" />
                <div class="control-group">
					<label class="control-label" asp-for="DataDeCriacao">Data</label>
					<div class="controls">
						<input asp-for="DataDeCriacao" type="text" id="basicinput" class="span8" disabled>
					</div>
				</div>

                 <div class="control-group">
					<label class="control-label" asp-for="SolicitanteID">Solicitante</label>
					<div class="controls">
						<select asp-for="SolicitanteID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarUsuarios,"UsuarioID", "Nome"))" disabled></select>
						<span asp-validation-for="SolicitanteID" class="text-danger"></span>
					</div>
				</div>

                <div class="control-group">
					<label class="control-label" asp-for="ClienteID">Cliente</label>
					<div class="controls">
						<select asp-for="ClienteID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarCliente,"ClienteID", "Nome"))"></select>
						<span asp-validation-for="ClienteID" class="text-danger"></span>
					</div>
				</div>
                
				<div class="control-group">
					<label class="control-label" asp-for="DepartamentoID">Departamento</label>
					<div class="controls">
						<select asp-for="DepartamentoID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarDepartamentos,"DepartamentoID", "Nome"))"></select>
						<span asp-validation-for="DepartamentoID" class="text-danger"></span>
					</div>
				</div>

                 <div class="control-group">
					<label class="control-label" asp-for="UsuarioID">Usuário</label>
					<div class="controls">
						<select asp-for="UsuarioID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarUsuarios,"UsuarioID", "Nome"))"></select>
						<span asp-validation-for="UsuarioID" class="text-danger"></span>
					</div>
				</div>

                <div class="control-group">
					<label class="control-label" asp-for="Status">Status</label>
					<div class="controls">
						        <select class="form-dropdown"  onchange="AlterarCor(this.value)" asp-for="Status" asp-items="Html.GetEnumSelectList<unipaulistana.model.StatusSolicitacao>()">
                                </select>
						<span asp-validation-for="Status" class="text-danger"></span>
					</div>
				</div>

				
				<div class="control-group">
					<label class="control-label" asp-for="Descricao">Descrição</label>
					<div class="controls">
						<textarea asp-for="Descricao" type="text" id="basicinput" placeholder="descrição" class="span8" rows="8"></textarea>
						<span asp-validation-for="Descricao" class="text-danger"></span>
					</div>
				</div>
			
				@if((int)Model.Status != 4)
				{
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">Salvar</button>
						</div>
					</div>
				}

				
			</form>
		</div>
	</div>				
</div><!--/.content-->

	@if((int)Model.Status != 4)
	{
		@await Component.InvokeAsync("SolicitacaoItensInserir", new { solicitacaoID = Model.SolicitacaoID })
	}

@await Component.InvokeAsync("SolicitacaoItens", new { solicitacaoID = Model.SolicitacaoID })

<script>
        const nao_iniciado = 1;
        const em_analise = 2;
        const em_andamento = 3;
        const concluido = 4;
    
    function AlterarCor(valor)
    {
        if(valor==nao_iniciado)
	    {
		    document.getElementById('Status').style.backgroundColor="red";
	    }
        else if(valor == em_analise)
        {
            document.getElementById('Status').style.backgroundColor="blue";
        }
        else if(valor == em_andamento)
        {
            document.getElementById('Status').style.backgroundColor="orange";
        }
        else if(valor == concluido)
        {
            document.getElementById('Status').style.backgroundColor="green";
        }
    }

    function onloadPage() {
        this.AlterarCor(document.getElementById('Status').value);
    }
    
    window.onload = onloadPage;

</script>

<style>
    .form-dropdown {
        color: #ffffff !important;
    }
</style>

unipaulistana.web/Views/Solicitacao/Criar.cshtml
@model unipaulistana.model.Solicitacao

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Criar nova solicitação</h3>
		</div>
		<div class="module-body">
			<form asp-action="Criar" class="form-horizontal row-fluid">
				<div class="control-group">
					<label class="control-label" asp-for="ClienteID">Cliente</label>
					<div class="controls">
						<select asp-for="ClienteID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarCliente,"ClienteID", "Nome"))"></select>
						<span asp-validation-for="ClienteID" class="text-danger"></span>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" asp-for="DepartamentoID">Departamento</label>
					<div class="controls">
						<select asp-for="DepartamentoID" class="form-control" asp-items="@(new SelectList(@ViewBag.ListarDepartamentos,"DepartamentoID", "Nome"))"></select>
						<span asp-validation-for="DepartamentoID" class="text-danger"></span>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" asp-for="Descricao">Descrição</label>
					<div class="controls">
						<textarea asp-for="Descricao" type="text" id="basicinput" placeholder="descrição" class="span8" rows="5"></textarea>
						<span asp-validation-for="Descricao" class="text-danger"></span>
					</div>
				</div>
			
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn">Salvar</button>
					</div>
				</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->
		
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

unipaulistana.web/Views/Solicitacao/Index.cshtml
@model unipaulistana.model.SolicitacaoPesquisar
@using unipaulistana.web.extensions

<br/>

<div class="btn-group">  
                <a id="createEditCustomerModal" asp-action="Index" class="btn btn-warning">  
                    <i class="glyphicon glyphicon-plus"></i>  Exibir minhas solicitações em aberto
                </a>  
            </div>  

            <br/>
            <br/>

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Pesquisar</h3>
		</div>
		<div class="module-body">
			<form asp-action="Index" class="form-horizontal row-fluid">
                <div class="control-group">
					<label class="control-label" asp-for="Status">Status</label>
					<div class="controls">
						        <select class="form-dropdown"  asp-for="Status" asp-items="Html.GetEnumSelectList<unipaulistana.model.StatusSolicitacao>()">
                                </select>
						<span asp-validation-for="Status" class="text-danger"></span>
					</div>
				</div>
				
		
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn btn-primary">Pesquisar</button>
					</div>
				</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->

<br/>


@Html.Partial("_ErrorSummary")


<div class="top-buffer"></div>  
<div class="panel panel-primary">  
    <h3>Lista de solicitações</h3>
    <div class="panel-body">  
        @if(User.HasPermission("PermiteCriarSolicitacao")){
            <div class="btn-group">  
                <a id="createEditCustomerModal" asp-action="Criar" class="btn btn-primary">  
                    <i class="glyphicon glyphicon-plus"></i>  Adicionar
                </a>  
            </div>  
        }
        <br/>
        <br/>

        <div class="module">
					
        <div class="module-body table"> 
        <table  cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">  
            <thead>  
                <tr>
                    <th>Data</th> 
                    <th>Cliente</th>   
                    <th>Usuário</th>                      
                    <th>Departamento</th>   
                    <th>Status</th>        
                    <th>Descrição</th>                      
                    <th></th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in ViewBag.ListarSolicitacoes)  
                {  
                    <tr >  
                        <td>@item.DataDeCriacao</td>  
                        <td>@item.NomeCliente</td>  
                        <td>@item.NomeUsuario</td>  
                        <td>@item.NomeDepartamento</td>  
                        
                        @if((int)item.Status == 1)
                        {
                            <td><span style="color:red">Não iniciado</span></td>  
                        }
                        else if((int)item.Status == 2)
                        {
                            <td><span style="color:blue">em analise</span></td>  
                        } 
                        else if((int)item.Status == 3)
                        {
                            <td><span style="color:orange">Em andamento</span></td>  
                        } 
                        else if((int)item.Status == 4)
                        {
                            <td><span style="color:green">Concluído</span></td>  
                        } 
                        else
                        {
                            <td><span style="color:blue">Não cadastrado</span></td>  
                        }
                        
                        <td>@item.Descricao</td>  
                        <td>  
                            @if(User.HasPermission("PermiteAlterarSolicitacao")){
                                
                                if((int)item.Status == 4)
                                {
                                    <a id="editarUsuario" asp-action="Alterar" asp-route-id= "@item.SolicitacaoID" class="btn btn-info">  
                                    <i class="glyphicon glyphicon-pencil"></i>  Visualizar  
                                </a>

                                }
                                else
                                {
<a id="editarUsuario" asp-action="Alterar" asp-route-id= "@item.SolicitacaoID" class="btn btn-info">  
                                    <i class="glyphicon glyphicon-pencil"></i>  Alterar  
                                </a>
                                }
                                
                                
                            }
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  
        </div> 
        </div>
    </div>  
</div>  
  
<script src="@Url.Content("~/js/datatables/jquery.dataTables.js")"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>