unipaulistana.web/Controllers/ClienteController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;

    [Authorize]
    public class ClienteController : Controller
    {
        public ClienteController(IClienteService clienteService)
        {
            this.clienteService = clienteService;
        }

        readonly IClienteService clienteService;

        [Authorize(Policy="PermiteListarCliente")]
        public IActionResult Index()
        { 
            if(TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            } 

            return View(this.clienteService.ObterTodos());
        }
        
        [Authorize(Policy="PermiteCriarCliente")]
        public IActionResult Criar()
        {
             return View();
        }

        [HttpPost]
        public IActionResult Criar(Cliente dados)
        {
            if (!ModelState.RemoveKeyModelState("ClienteID").IsValid)
                return View(dados);

            try
            {
                this.clienteService.Adicionar(dados);
                TempData["mensagemIndex"] = "Cliente inserido com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteAlterarCliente")]
        public IActionResult Alterar(int id)
        {
            if(TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            } 

            return View(this.clienteService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(Cliente dados)
        {
            if (!ModelState.IsValid)
                return View(dados);

            try
            {
                this.clienteService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Cliente atualizado com sucesso."; 
                return RedirectToAction("Alterar", dados.ClienteID);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteExcluirCliente")]
        public IActionResult Excluir(int id)
        {
            return View(this.clienteService.ObterPorID(id));
        }

        [HttpPost]
        public ActionResult Excluir(Cliente dados)
        {
            try
            {
                this.clienteService.Excluir(dados.ClienteID);
                TempData["mensagemIndex"] = "Cliente excluído com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("error", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                return View(dados);
            }
        }
    }
}

unipaulistana.web/Controllers/SolicitacaoController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using System.IO;
    using unipaulistana.web.Helper;
    using Microsoft.AspNetCore.Hosting;
    using unipaulistana.web.extensions;

    [Authorize]
    public class SolicitacaoController : Controller
    {
        public SolicitacaoController(ISolicitacaoService solicitacaoService,
                                    IClienteService clienteService,
                                    IUsuarioService usuarioService,
                                    IDepartamentoService departamentoService,
                                    IHostingEnvironment hostingEnvironment)
        {
            this.solicitacaoService = solicitacaoService;
            this.clienteService = clienteService;
            this.usuarioService = usuarioService;
            this.hostingEnvironment = hostingEnvironment;
            this.departamentoService = departamentoService;
        }

        readonly ISolicitacaoService solicitacaoService;
        readonly IClienteService clienteService;
        readonly IUsuarioService usuarioService;
        readonly IDepartamentoService departamentoService;
        readonly IHostingEnvironment hostingEnvironment;

        [Authorize(Policy = "PermiteListarSolicitacao")]
        public IActionResult Index()
        {
            if (TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            }

            ViewBag.ListarSolicitacoes = this.solicitacaoService.ObterStatusEmAbertoPorUsuario(User.GetUserID());
            return View();
        }


        [HttpPost]
        public IActionResult Index(SolicitacaoPesquisar solicitacaoPesquisar)
        {
            ViewBag.ListarSolicitacoes = this.solicitacaoService.Filtrar(solicitacaoPesquisar);
            return View();
        }

        [Authorize(Policy = "PermiteCriarSolicitacao")]
        public IActionResult Criar()
        {
            AtualizarListas();
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Solicitacao dados)
        {
            try
            {
                this.solicitacaoService.Adicionar(dados, User.GetUserID());
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        [Authorize(Policy = "PermiteAlterarSolicitacao")]
        public IActionResult Alterar(int id)
        {
            if (TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            }

            AtualizarListas();
            return View(this.solicitacaoService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(Solicitacao dados)
        {
            try
            {
                this.solicitacaoService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Solicitação atualizada com sucesso.";
                return RedirectToAction("Alterar", dados.SolicitacaoID);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar a solicitação:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        void AtualizarListas()
        {
            ViewBag.ListarDepartamentos = this.departamentoService.ObterTodos();
            ViewBag.ListarCliente = this.clienteService.ObterTodos();
            ViewBag.ListarUsuarios = this.usuarioService.ObterTodos();
        }

        [Authorize(Policy = "PermiteConcluirSolicitacao")]
        public IActionResult ConcluirSolicitacao(int id)
        {
            return View();
        }


        [HttpPost]
        [Authorize(Policy = "PermiteAlterarSolicitacao")]
        public IActionResult AdicionarItem(SolicitacaoItem solicitacaoItem)
        {
            if (!string.IsNullOrEmpty(solicitacaoItem.Descricao))
                this.solicitacaoService.AdicionarItem(solicitacaoItem, User.GetUserID());
                
            return RedirectToAction("Alterar", new { id = solicitacaoItem.SolicitacaoID });
        }
    }
}

unipaulistana.web/Controllers/UsuarioController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using System.IO;
    using unipaulistana.web.Helper;
    using Microsoft.AspNetCore.Hosting;
    using unipaulistana.web.extensions;

    [Authorize]
    public class UsuarioController : Controller
    {
        public UsuarioController(IUsuarioService usuarioService,
                                 IDepartamentoService departamentoService,
                                 IGrupoDeSegurancaService grupoDeSegurancaService,
                                 IHostingEnvironment hostingEnvironment)
        {
            this.usuarioService = usuarioService;
            this.hostingEnvironment = hostingEnvironment;
            this.departamentoService = departamentoService;
            this.grupoDeSegurancaService = grupoDeSegurancaService;
        }

        readonly IUsuarioService usuarioService;
        readonly IDepartamentoService departamentoService;
        readonly IGrupoDeSegurancaService grupoDeSegurancaService;
        readonly IHostingEnvironment hostingEnvironment;

        [Authorize(Policy="PermiteListarUsuario")]
        public IActionResult Index()
        {
            if (TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            }

            return View(this.usuarioService.ObterTodos());
        }

        [Authorize(Policy="PermiteCriarUsuario")]
        public IActionResult Criar()
        {
            AtualizarListas();
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Usuario dados)
        {
            try
            {
                this.usuarioService.Adicionar(dados);
                TempData["mensagemIndex"] = "Usuário inserido com sucesso.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        public IActionResult ImagemUsuario()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ImagemUsuario(List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);
            if (size <= 0)
            {
                TempData["mensagem"] = "Selecione um arquivo!!!";
                return View();
            }


            var filePath = Path.GetTempFileName();

            try
            {
                foreach (var formFile in files)
                {
                    string novoArquivo = FileHelper.GetUniqueFileName(formFile.FileName);
                    var uploads = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    var fullPath = Path.Combine(uploads, novoArquivo);
                    formFile.CopyTo(new FileStream(fullPath, FileMode.Create));

                    this.usuarioService.AtualizarFoto(User.GetUserID(), novoArquivo);
                }

                TempData["mensagem"] = "Arquivo enviado com sucesso.";
                return RedirectToAction("ImagemUsuario");
            }
            catch (Exception ex)
            {
                TempData["mensagem"] = string.Format("Ocorreu um erro:{0}", ex.Message);
                return View();
            }
        }

        [Authorize(Policy="PermiteAlterarUsuario")]
        public IActionResult Alterar(int id)
        {
            if (TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            }

            AtualizarListas();
            return View(this.usuarioService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(Usuario dados)
        {
            try
            {
                this.usuarioService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Usuário atualizado com sucesso.";
                return RedirectToAction("Alterar", dados.UsuarioID);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                AtualizarListas();
                return View(dados);
            }
        }

        void AtualizarListas()
        {
            ViewBag.ListarDepartamentos = this.departamentoService.ObterTodos();
            ViewBag.ListarGruposDeSeguranca = this.grupoDeSegurancaService.ObterTodos();
        }

        [Authorize(Policy="PermiteExcluirUsuario")]
        public IActionResult Excluir(int id)
        {
            return View(this.usuarioService.ObterPorID(id));
        }

        [HttpPost]
        public ActionResult Excluir(Usuario dados)
        {
            try
            {
                this.usuarioService.Excluir(dados.UsuarioID);
                TempData["mensagemIndex"] = "Usuário excluído com sucesso.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o usuário:{0}", ex.Message));
                return View(dados);
            }
        }

        public IActionResult NovaSenha()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NovaSenha(NovaSenha novaSenha)
        {
            try
            {
                this.usuarioService.AtualizarSenha(User.GetUserID(), novaSenha.SenhaAnterior, novaSenha.Senha);
                ViewBag.Sucesso = "Senha atualizada com sucesso.";
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar a senha:{0}", ex.Message));
                return View();
            }
        }

        [Authorize(Policy="PermiteAlterarSenhaViaAdminUsuario")]
        public IActionResult AlterarSenhaViaAdmin(int id)
        {
            var usuario = new NovaSenhaAlteradaPorAdmin(id);
            return View(usuario);
        }

        [HttpPost]
        public IActionResult AlterarSenhaViaAdmin(NovaSenhaAlteradaPorAdmin novaSenha)
        {
            try
            {
                this.usuarioService.AtualizarSenha(novaSenha.UserID, novaSenha.Senha);
                ViewBag.Sucesso = "Senha atualizada com sucesso.";
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar a senha:{0}", ex.Message));
                return View();
            }
        }
    }
}

unipaulistana.web/Views/Shared/_ErrorSummary.cshtml
@if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Any())
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <p>Atenção, verifique as instruções a seguir:</p>
        @Html.ValidationSummary(true, "", new { @Class = "validation" })
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
     <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <p>@ViewBag.Sucesso</p>
    </div>
}

unipaulistana.web/Views/Shared/_Layout.cshtml
@using unipaulistana.web.extensions

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SAC - Sistema de atendimento ao cliente</title>

        <link type="text/css" href="@Url.Content("~/bootstrap/css/bootstrap.min.css")" rel="stylesheet">
        <link type="text/css" href="@Url.Content("~/bootstrap/css/bootstrap-responsive.min.css")" rel="stylesheet">
        <link type="text/css" href="@Url.Content("~/css/theme.css")" rel="stylesheet">
        <link type="text/css" href="@Url.Content("~/images/icons/css/font-awesome.css")" rel="stylesheet">
        <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>
</head>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
					<i class="icon-reorder shaded"></i>
				</a>

			  	<a class="brand" href="@Url.Action("Dashboard", "Home")">
			  		SAC - Sistema de atendimento ao cliente
			  	</a>

				<div class="nav-collapse collapse navbar-inverse-collapse">
				
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
							<ul class="dropdown-menu">
								
								@if(User.HasPermission("PermiteListarUsuario"))
								{
									<li><a href="@Url.Action("Index", "Usuario")">Usuários</a></li>
								}
								
								@if(User.HasPermission("PermiteListarCliente"))
								{
									<li><a href="@Url.Action("Index", "Cliente")">Clientes</a></li>
								}

								@if(User.HasPermission("PermiteListarDepartamento"))
								{
									<li><a href="@Url.Action("Index", "Departamento")">Departamento</a></li>
								}
								
								@if(User.HasPermission("PermiteListarGrupoDeSeguranca"))
								{
									<li><a href="@Url.Action("Index", "GrupoDeSeguranca")">Grupo de segurança</a></li>
								}

								@if(User.HasPermission("PermiteListarSolicitacao"))
								{
									<li><a href="@Url.Action("Index", "Solicitacao")">Solicitação</a></li>
								}
							</ul>
						</li>
				
						<li class="nav-user dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<img src="@Html.Raw(Url.Content("~/images/" + @User.GetPicture()))" class="nav-avatar" />
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><a href="@Url.Action("ImagemUsuario", "Usuario")">Alterar foto</a></li>
								<li><a href="@Url.Action("NovaSenha", "Usuario")">Alterar senha</a></li>
								<li class="divider"></li>
								<li><a href="@Url.Action("Logout","Home")">Sair</a></li>
							</ul>
						</li>
					</ul>
				</div><!-- /.nav-collapse -->
			</div>
		</div><!-- /navbar-inner -->
	</div><!-- /navbar -->

<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; SAC 2018 - unipaulistana/4° Semestre</p>
        </footer>
    </div>

  
    @RenderSection("Scripts", required: false)
</body>
</html>

<script src="@Url.Content("~/js/jquery-1.9.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/jquery-ui-1.10.1.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/bootstrap/js/bootstrap.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/flot/jquery.flot.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/flot/jquery.flot.resize.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/datatables/jquery.dataTables.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/common.js")" type="text/javascript"></script>