unipaulistana.web/Controllers/DepartamentoController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;

    [Authorize]
    public class DepartamentoController : Controller
    {
        public DepartamentoController(IDepartamentoService departamentoService)
        {
            this.departamentoService = departamentoService;
        }

        readonly IDepartamentoService departamentoService;

        [Authorize(Policy="PermiteListarDepartamento")]
        public IActionResult Index()
        { 
            if(TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            } 

            return View(this.departamentoService.ObterTodos());
        }
        
        [Authorize(Policy="PermiteCriarDepartamento")]
        public IActionResult Criar()
        {
             return View();
        }

        [HttpPost]
        public IActionResult Criar(Departamento dados)
        {
            if (!ModelState.RemoveKeyModelState("DepartamentoID").IsValid)
                return View(dados);

            try
            {
                this.departamentoService.Adicionar(dados);
                TempData["mensagemIndex"] = "Departamento inserido com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o departamento:", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteAlterarDepartamento")]
        public IActionResult Alterar(int id)
        {
            if(TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            } 

            return View(this.departamentoService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(Departamento dados)
        {
            if (!ModelState.IsValid)
                return View(dados);

            try
            {
                this.departamentoService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Departamento atualizado com sucesso."; 
                return RedirectToAction("Alterar", dados.DepartamentoID);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o departamento:{0}", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteExcluirDepartamento")]
        public IActionResult Excluir(int id)
        {
            return View(this.departamentoService.ObterPorID(id));
        }

        [HttpPost]
        public ActionResult Excluir(Departamento dados)
        {
            try
            {
                this.departamentoService.Excluir(dados.DepartamentoID);
                TempData["mensagemIndex"] = "Departamento excluído com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar excluir o departamento:{0}", ex.Message));
                return View(dados);
            }
        }
    }
}

unipaulistana.web/Views/Departamento/Alterar.cshtml
@model unipaulistana.model.Departamento

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Departamento" >Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")


<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Alterar informações do departamento</h3>
		</div>
		<div class="module-body">
			<form asp-action="Alterar" class="form-horizontal row-fluid">
				
				<input type="hidden" asp-for="DepartamentoID" />
				
				<div class="control-group">
					<label class="control-label" asp-for="Nome">Nome</label>
						<div class="controls">
							<input asp-for="Nome" type="text" id="basicinput" placeholder="Type something here..." class="span8">
							<span asp-validation-for="Nome" class="text-danger"></span>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">Salvar</button>
						</div>
					</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->
		
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

unipaulistana.web/Views/Departamento/Criar.cshtml
@model unipaulistana.model.Departamento

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")


<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Inserir novo departamento</h3>
		</div>
		<div class="module-body">
			<form asp-action="Criar" class="form-horizontal row-fluid">
				
				<div class="control-group">
					<label class="control-label" asp-for="Nome">Nome</label>
						<div class="controls">
							<input asp-for="Nome" type="text" id="basicinput" placeholder="nome" class="span8">
							<span asp-validation-for="Nome" class="text-danger"></span>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">Salvar</button>
						</div>
					</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->
		

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

unipaulistana.web/Views/Departamento/Excluir.cshtml
@model unipaulistana.model.Departamento

@{
    ViewBag.Title = "Excluir";
}

<br />
@Html.Partial("_ErrorSummary")
<div class="col-lg-12">
    <div class="ibox">
   
      <h5 class="titulo">Tem certeza de que deseja excluir esse registro ?</h5>
        <div class="ibox-content">
          <br /><br />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nome)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nome)
                </dd>
            </dl>

            <form asp-action="Excluir" method="POST">
                @Html.HiddenFor(x => x.DepartamentoID)
                @Html.HiddenFor(x => x.Nome)

               <div class="rodapebtn">
                       <hr />
                    <input type="submit" id="btnExcluir" value="Confirmar Exclusão" class="btn btn-danger" />
                </div>
            </form>

            <br />
            <br />
            <br />
            <div class="form-group">
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </div>
    </div>
</div>
<div style="clear:both" ></div>

unipaulistana.web/Views/Departamento/Index.cshtml
@model IEnumerable<unipaulistana.model.Departamento>  

@using unipaulistana.web.extensions

<br/>

@Html.Partial("_ErrorSummary")

<div class="top-buffer"></div>  
<div class="panel panel-primary">  
    <h3>Lista de departamento</h3>
    <div class="panel-body">  
        
        @if(User.HasPermission("PermiteCriarDepartamento")){
            <div class="btn-group">  
                <a id="createEditCustomerModal" asp-action="Criar" class="btn btn-primary">  
                    <i class="glyphicon glyphicon-plus"></i>  Adicionar
                </a>  
            </div>  
        }
        <br/>
        <br/>
        

        <div class="module">
					
        <div class="module-body table"> 
        <table  cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">  
            <thead>  
                <tr>
                    <th>ID</th>  
                    <th>Nome</th>                      
                    <th></th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in Model)  
                {  
                    <tr>  
                        <td>@Html.DisplayFor(modelItem => item.DepartamentoID)</td>  
                        <td>@Html.DisplayFor(modelItem => item.Nome)</td>  
                        <td>  
                            
                            @if(User.HasPermission("PermiteAlterarDepartamento")){
                                <a id="editCustomerModal" asp-action="Alterar" asp-route-id= "@item.DepartamentoID" class="btn btn-info">  
                                    <i class="glyphicon glyphicon-pencil"></i>  Alterar  
                                </a>  
                            }

                            @if(User.HasPermission("PermiteExcluirDepartamento")){
                                <a id="deleteCustomerModal" asp-action="Excluir" asp-route-id= "@item.DepartamentoID" class="btn btn-danger">  
                                    <i class="glyphicon glyphicon-trash"></i>  Excluir  
                                </a>  
                            }
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  
        </div> 
        </div>
    </div>  
</div>  
  
<script src="@Url.Content("~/js/datatables/jquery.dataTables.js")"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>