unipaulistana.web/Controllers/GrupoDeSegurancaController.cs
namespace unipaulistana.web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using unipaulistana.model;
    using Microsoft.AspNetCore.Authorization;

    [Authorize]
    public class GrupoDeSegurancaController : Controller
    {
        public GrupoDeSegurancaController(IGrupoDeSegurancaService grupoDeSegurancaService, IDiretivaSegurancaService diretivaSegurancaService)
        {
            this.grupoDeSegurancaService = grupoDeSegurancaService;
            this.diretivaSegurancaService = diretivaSegurancaService;
        }

        readonly IGrupoDeSegurancaService grupoDeSegurancaService;
        readonly IDiretivaSegurancaService diretivaSegurancaService;

        [Authorize(Policy="PermiteListarGrupoDeSeguranca")]
        public IActionResult Index()
        { 
            if(TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            } 

            return View(this.grupoDeSegurancaService.ObterTodos());
        }
        
        [Authorize(Policy="PermiteCriarGrupoDeSeguranca")]
        public IActionResult Criar()
        {
             return View();
        }

        [HttpPost]
        public IActionResult Criar(GrupoDeSeguranca dados)
        {
            if (!ModelState.RemoveKeyModelState("GrupoDeSegurancaID").IsValid)
                return View(dados);

            try
            {
                this.grupoDeSegurancaService.Adicionar(dados);
                TempData["mensagemIndex"] = "Grupo inserido com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o grupo:{0}", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteAlterarGrupoDeSeguranca")]
        public IActionResult Alterar(int id)
        {
            if(TempData["mensagemEdicao"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemEdicao"];
            } 

            return View(this.grupoDeSegurancaService.ObterPorID(id));
        }

        [HttpPost]
        public IActionResult Alterar(GrupoDeSeguranca dados)
        {
            if (!ModelState.IsValid)
                return View(dados);

            try
            {
                this.grupoDeSegurancaService.Atualizar(dados);
                TempData["mensagemEdicao"] = "Grupo atualizado com sucesso."; 
                return RedirectToAction("Alterar", dados.GrupoDeSegurancaID);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar atualizar o grupo:{0}", ex.Message));
                return View(dados);
            }
        }

        [Authorize(Policy="PermiteExcluirGrupoDeSeguranca")]
        public IActionResult Excluir(int id)
        {
            return View(this.grupoDeSegurancaService.ObterPorID(id));
        }

        [HttpPost]
        public ActionResult Excluir(GrupoDeSeguranca dados)
        {
            try
            {
                this.grupoDeSegurancaService.Excluir(dados.GrupoDeSegurancaID);
                TempData["mensagemIndex"] = "Grupo excluído com sucesso."; 
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar excluir o grupo:{0}", ex.Message));
                return View(dados);
            }
        }

        public IActionResult Permissoes(int id)
        {
            if(TempData["mensagemIndex"] != null)
            {
                ViewBag.Sucesso = TempData["mensagemIndex"];
            } 

            InicializarViewBagsDeDiretivasDeSeguranca(id);
            return View(new DiretivaSeguranca(id)); 
        }

        [HttpPost]
        public IActionResult Permissoes(DiretivaSeguranca dados)
        {   
            try
            {
                this.diretivaSegurancaService.AdicionarPermissao(dados);
                TempData["mensagemIndex"] = "Permissão adicionada com sucesso."; 
                return RedirectToAction("Permissoes", new { id=dados.GrupoSegurancaID });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar adicionar uma permissão:{0}", ex.Message));
                InicializarViewBagsDeDiretivasDeSeguranca(dados.GrupoSegurancaID);
                return View(dados);
            }
        }

        public IActionResult RemoverPermissao(int grupoID, int diretivaID)
        {
            try
            {
                this.diretivaSegurancaService.RemoverPermissao(new DiretivaSeguranca(grupoID, diretivaID));
                TempData["mensagemIndex"] = "Permissão excluída com sucesso."; 
                return RedirectToAction("Permissoes", new { id=grupoID } );
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro ao tentar adicionar uma permissão:{0}", ex.Message));
                return RedirectToAction("Permissoes", new { id=grupoID });
            }
        }

        void InicializarViewBagsDeDiretivasDeSeguranca(int id)
        {
            ViewBag.listaDeDiretivasAssociadasAoGrupo = this.diretivaSegurancaService.ObterDiretivasAssociadasGrupo(id);
            ViewBag.listaDeDiretivasNaoAssociadasAoGrupo = this.diretivaSegurancaService.ObterDiretivasNaoAssociadasGrupo(id);
            ViewBag.NomeDoGrupo = this.grupoDeSegurancaService.ObterPorID(id).Nome;
        }
    }
}

unipaulistana.web/Views/GrupoDeSeguranca/Alterar.cshtml
@model unipaulistana.model.GrupoDeSeguranca

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="GrupoDeSeguranca" >Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")


<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Alterar informações do grupo de segurança</h3>
		</div>
		<div class="module-body">
			<form asp-action="Alterar" class="form-horizontal row-fluid">
				
				<input type="hidden" asp-for="GrupoDeSegurancaID" />
				
				<div class="control-group">
					<label class="control-label" asp-for="Nome">Nome</label>
						<div class="controls">
							<input asp-for="Nome" type="text" id="basicinput" placeholder="Type something here..." class="span8">
							<span asp-validation-for="Nome" class="text-danger"></span>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">Salvar</button>
						</div>
					</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->
		
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

unipaulistana.web/Views/GrupoDeSeguranca/Criar.cshtml
@model unipaulistana.model.GrupoDeSeguranca

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="GrupoDeSeguranca">Voltar</a>
</div>
<br/>


@Html.Partial("_ErrorSummary")


<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Inserir novo grupo de segurança</h3>
		</div>
		<div class="module-body">
			<form asp-action="Criar" class="form-horizontal row-fluid">
				
				<div class="control-group">
					<label class="control-label" asp-for="Nome">Nome</label>
						<div class="controls">
							<input asp-for="Nome" type="text" id="basicinput" placeholder="nome" class="span8">
							<span asp-validation-for="Nome" class="text-danger"></span>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">Salvar</button>
						</div>
					</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->
		

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

unipaulistana.web/Views/GrupoDeSeguranca/Excluir.cshtml
@model unipaulistana.model.GrupoDeSeguranca

@{
    ViewBag.Title = "Excluir";
}

<br />
@Html.Partial("_ErrorSummary")
<div class="col-lg-12">
    <div class="ibox">
   
      <h5 class="titulo">Tem certeza de que deseja excluir esse registro ?</h5>
        <div class="ibox-content">
          <br /><br />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nome)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nome)
                </dd>
            </dl>

            <form asp-action="Excluir" method="POST">
                @Html.HiddenFor(x => x.GrupoDeSegurancaID)
                @Html.HiddenFor(x => x.Nome)

               <div class="rodapebtn">
                       <hr />
                    <input type="submit" id="btnExcluir" value="Confirmar Exclusão" class="btn btn-danger" />
                </div>
            </form>

            <br />
            <br />
            <br />
            <div class="form-group">
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </div>
    </div>
</div>
<div style="clear:both" ></div>

unipaulistana.web/Views/GrupoDeSeguranca/Index.cshtml
@model IEnumerable<unipaulistana.model.GrupoDeSeguranca>  

@using unipaulistana.web.extensions

<br/>

@Html.Partial("_ErrorSummary")

<div class="top-buffer"></div>  
<div class="panel panel-primary">  
    <h3>Lista de grupos de segurança</h3>
    <div class="panel-body">  
        
        @if(User.HasPermission("PermiteCriarGrupoDeSeguranca")){
            <div class="btn-group">  
                <a id="create" asp-action="Criar" class="btn btn-primary">  
                    <i class="glyphicon glyphicon-plus"></i>  Adicionar
                </a>  
            </div> 
        } 
        <br/>
        <br/>

        <div class="module">
					
        <div class="module-body table"> 
        <table  cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">  
            <thead>  
                <tr>
                    <th>ID</th>  
                    <th>Nome</th>                      
                    <th></th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in Model)  
                {  
                    <tr>  
                        <td>@Html.DisplayFor(modelItem => item.GrupoDeSegurancaID)</td>  
                        <td>@Html.DisplayFor(modelItem => item.Nome)</td>  
                        <td>  
                            
                            @if(User.HasPermission("PermiteAlterarGrupoDeSeguranca")){
                                <a id="edit" asp-action="Alterar" asp-route-id= "@item.GrupoDeSegurancaID" class="btn btn-info">  
                                    <i class="glyphicon glyphicon-pencil"></i>  Alterar  
                                </a>  
                            }

                            @if(User.HasPermission("PermiteExcluirGrupoDeSeguranca")){
                                <a id="delete" asp-action="Excluir" asp-route-id= "@item.GrupoDeSegurancaID" class="btn btn-danger">  
                                    <i class="glyphicon glyphicon-trash"></i>  Excluir  
                                </a> 
                            }

                            @if(User.HasPermission("PermiteAssociarDiretivaGrupoDeSeguranca")){
                                <a id="delete" asp-action="Permissoes" asp-route-id= "@item.GrupoDeSegurancaID" class="btn btn-warning">  
                                    <i class="glyphicon glyphicon-trash"></i>  Permissões  
                                </a>  
                            }
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  
        </div> 
        </div>
    </div>  
</div>  
  
<script src="@Url.Content("~/js/datatables/jquery.dataTables.js")"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>

unipaulistana.web/Views/GrupoDeSeguranca/Permissoes.cshtml
@model unipaulistana.model.DiretivaSeguranca

<br/>
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br/>

<style>
	h1 {
  		color:  red;
	}
</style>

<span>Grupo de segurança:<h1>@ViewBag.NomeDoGrupo</h1></span>

@Html.Partial("_ErrorSummary")

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Adicionar permissão</h3>
		</div>
		<div class="module-body">
			<form asp-action="Permissoes" class="form-horizontal row-fluid">
				
                <input type="hidden" asp-for="GrupoSegurancaID" />
			
				
				<div class="control-group">
					<label class="control-label" asp-for="DiretivaSegurancaID">Diretiva</label>
					<div class="controls">
						<select asp-for="DiretivaSegurancaID" class="form-control" asp-items="@(new SelectList(@ViewBag.listaDeDiretivasNaoAssociadasAoGrupo,"DiretivaSegurancaID", "Nome"))"></select>
						<span asp-validation-for="DiretivaSegurancaID" class="text-danger"></span>
					</div>
				</div>
				
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn">Adicionar</button>
					</div>
				</div>
			</form>
		</div>
	</div>				
</div><!--/.content-->

 <div class="module-body table"> 
        <table  cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">  
            <thead>  
                <tr>
                    <th>Nome</th>                      
                    <th></th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in ViewBag.listaDeDiretivasAssociadasAoGrupo)  
                {  
                    <tr>  
                        <td>@item.Nome</td>  
                        <td>  
                           @Html.ActionLink("Excluir", "RemoverPermissao", "GrupoDeSeguranca", new { grupoID=Model.GrupoSegurancaID, diretivaID=item.DiretivaSegurancaID }, new { @class="btn btn-danger" })
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  
        </div> 
		
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="@Url.Content("~/js/datatables/jquery.dataTables.js")"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>